spring.application.name=user-service
server.port=${USER_SERVICE_PORT:8085}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/userdb}
spring.data.mongodb.database=risktrace_user

spring.docker.compose.enabled=false

# --- JWT ---
JWT_SECRET=WnZrNHAzczV2OGV4cm9pYndxbm16bHBrZGpmaHNoYWpza2RscTU0ODk3MTIzem1uYmN2eA==
jwt.secret=${JWT_SECRET:QWERTYUIOPASDFGHJKLZXCVBNM123456}
jwt.expiration=86400000

# --- Email (Gmail SMTP) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME:risktrace001@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:rhhkxljaodastvin}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# --- App Config ---
app.frontend-url=${FRONTEND_URL:http://localhost:4200}
app.verification-token-expiry-hours=24
app.password-reset-token-expiry-hours=1