spring.application.name=log-service
server.port=${LOG_SERVICE_PORT:8087}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
# Log-service stores logs in logdb
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/logdb}

# Secondary data source: Points to the same Atlas DB to find site API keys
app.sitedb.uri=${MONGODB_URI:mongodb://localhost:27017/sitedb}