spring.application.name=site-service
server.port=${SITE_SERVICE_PORT:8086}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/sitedb}
spring.data.mongodb.database=risktrace_site